version: '3'
services:
  back:
    build: './back'
    networks:
      deploy_net:
        ipv4_address: 172.28.1.1
  front:
    build: './web'
    ports:
      - 8080:80
    networks:
      deploy_net:
        ipv4_address: 172.28.1.2
networks:
  deploy_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
